services:
  db:
    container_name: mysql-cont
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: db_name
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_pass
    ports:
      - 3306:3306
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      - mynetwork

  python:
    container_name: python-cont
    build: ./python
    image: compose_mysql/python:1
    depends_on:
      - db
    networks:
      - mynetwork
    volumes:
      - ./python/scripts:/usr/src/app/scripts


networks:
  mynetwork:
    driver: bridge